//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP1101
{
    using System;
    using System.Collections.Generic;
    
    public partial class История_работы
    {
        public int id { get; set; }
        public int id_сотрудника { get; set; }
        public int id_должности { get; set; }
        public int id_отдела { get; set; }
        public System.DateTime Дата_начала { get; set; }
        public Nullable<System.DateTime> Дата_окончания { get; set; }
    
        public virtual Должности Должности { get; set; }
        public virtual Отделы Отделы { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
