//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP1101
{
    using System;
    using System.Collections.Generic;
    
    public partial class Контакты
    {
        public int id { get; set; }
        public int id_сотрудника { get; set; }
        public string Телефон { get; set; }
        public string Email { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
